//
//  DataStore.swift
//  Contacts
//
//  Created by Виталий Гринчик on 10.01.23.
//

final class DataStore {
    
    static let shared = DataStore()

    let names = [
        "Oliver",
        "Jack",
        "Harry",
        "Jacob",
        "Charley",
        "Thomas",
        "George",
        "Oscar",
        "James",
        "William",
        "Anna",
        "Maria",
        "Sophia",
        "Catherine",
        "Victoria",
        "Alexandra",
        "Eva",
        "Diana",
        "Anastasia",
        "Veronica"
    ]

    let surnames = [
        "Smith",
        "Johnson",
        "Williams",
        "Jones",
        "Brown",
        "Davis",
        "Miller",
        "Wilson",
        "Moore",
        "Taylor",
        "Anderson",
        "Thomas",
        "Jackson",
        "White",
        "Harris",
        "Martin",
        "Thompson",
        "Garcia",
        "Martinez",
        "Robinson"
    ]

    let mailServices = [
        "gmail.com",
        "hotmail.com",
        "icloud.com",
        "yahoo.com",
        "mail.ru",
        "outlook.com"
    ]
    
    let countryCodes = [
        "Australian External Territories": "672",
        "Australia": "61",
        "Austria": "43",
        "Azerbaijan": "994",
        "Azores": "351",
        "Albania": "355",
        "Algeria": "21",
        "American Samoa": "684",
        "Angola": "244",
        "Anguilla": "1-264",
        "Andorra": "376",
        "Antigua and Barbuda": "1-268",
        "Argentina": "54",
        "Armenia": "374",
        "Aruba": "297",
        "Ascension": "247",
        "Afghanistan": "93",
        "Bahamas": "1-242",
        "Bangladesh": "880",
        "Barbados": "1-246",
        "Bahrain": "973",
        "Belize": "501",
        "Belarus": "375",
        "Belgium": "32",
        "Benin": "229",
        "Ivory Coast": "225",
        "Bermuda": "1-441",
        "Bulgaria": "359",
        "Bolivia": "591",
        "Bosnia and Herzegovina": "387",
        "Botswana": "267",
        "Brazil": "55",
        "British Virgin Islands": "1-284",
        "Brunei": "673",
        "Burkina Faso": "226",
        "Burundi": "257",
        "Bhutan": "975",
        "Vanuatu": "678",
        "Vatican": "39",
        "United Kingdom": "44",
        "Hungary": "36",
        "Venezuela": "58",
        "US Virgin Islands": "1-340",
        "East Timor": "62",
        "Vietnam": "84",
        "Gabonese Republic": "241",
        "Haiti": "509",
        "Guyana": "592",
        "Gambia": "220",
        "Ghana": "233",
        "Guatemala": "502",
        "Guinea": "224",
        "Guinea-Bissau": "245",
        "Germany": "49",
        "Gibraltar": "350",
        "Honduras": "504",
        "Hong Kong": "852",
        "Grenada": "1-473",
        "Greenland": "299",
        "Greece": "30",
        "Georgia": "995",
        "Guam": "671",
        "Denmark": "45",
        "Democratic Republic (ex. Zaire)": "243",
        "Djibouti": "253",
        "Diego Garcia": "246",
        "Dominica": "1-767",
        "Dominican Republic": "1-809",
        "Egypt": "20",
        "Zaire": "243",
        "Zambia": "260",
        "Zanzibar": "259",
        "Western Sahara": "21",
        "Western Samoa": "685",
        "Zimbabwe": "263",
        "Israel": "972",
        "India": "91",
        "Indonesia": "62",
        "Jordan": "962",
        "Iraq": "964",
        "Iran": "98",
        "Irish Republic": "353",
        "Iceland": "354",
        "Spain": "34",
        "Italy": "39",
        "Kazakhstan": "7",
        "Cayman Islands": "1-345",
        "Cambodia": "855",
        "Cameroon": "237",
        "Cape Verde": "238",
        "Qatar": "974",
        "Kenya": "254",
        "Cyprus": "357",
        "Kyrgyzstan": "996",
        "Kiribati Republic": "686",
        "China": "86",
        "Cocos Islands": "672",
        "Colombia": "57",
        "Comoros and Mayotte Island": "269",
        "Congo": "242",
        "Costa Rica": "506",
        "Cuba": "53",
        "Kuwait": "965",
        "Laos": "856",
        "Latvia": "371",
        "Lesotho": "266",
        "Liberia": "231",
        "Lebanon": "961",
        "Libya": "21",
        "Lithuania": "370",
        "Liechtenstein": "41",
        "Luxembourg": "352",
        "Mauritius": "230",
        "Mauritania": "222",
        "Madagascar": "261",
        "Macau": "853",
        "Macedonia": "389",
        "Malawi": "265",
        "Malaysia": "60",
        "Mali": "223",
        "Maldives": "960",
        "Malta": "356",
        "Morocco": "212",
        "Martinique": "596",
        "Marshall Islands": "692",
        "Mexico": "52",
        "Micronesia": "691",
        "Mozambique": "258",
        "Moldova": "373",
        "Monaco": "377",
        "Mongolia": "976",
        "Montserrat": "1-664",
        "Myanmar": "95",
        "Namibia": "264",
        "Nauru": "674",
        "Nepal": "977",
        "Niger": "227",
        "Nigeria": "234",
        "Netherlands Antilles": "599",
        "Netherlands": "31",
        "Nicaragua": "505",
        "Niue Islands": "683",
        "New Zealand": "64",
        "New Caledonia": "687",
        "Norway": "47",
        "Norfolk Island": "672",
        "Cook Islands": "682",
        "Saint Helena and Ascension Isl": "247",
        "United Arab Emirates": "971",
        "Oman": "968",
        "Pakistan": "92",
        "Palau": "680",
        "Panama": "507",
        "Papua New Guinea": "675",
        "Paraguay": "595",
        "Peru": "51",
        "Poland": "48",
        "Portugal": "351",
        "Puerto Rico": "1-787",
        "Reunion Islands": "262",
        "Christmas Island": "672",
        "Russia": "7",
        "Rwandese Republic": "250",
        "Romania": "40",
        "El Salvador": "503",
        "Republic of San Marino": "378",
        "San Marino": "39",
        "St. Lucia": "1-758",
        "Saudi Arabia": "966",
        "Swaziland": "268",
        "Svalbard and Jan Mayen Islands": "47",
        "Dem. Peoples Republic of Korea": "850",
        "Yemen, North": "967",
        "Northern Mariana Islands": "670",
        "Seychelles": "248",
        "Senegal": "221",
        "St. Vincent and the Grenadines": "1-784",
        "Saint Pierre et Miquelon": "508",
        "Sao Tome e Principe": "239",
        "St. Kitts and Nevis": "1-869",
        "Singapore": "65",
        "Syria": "963",
        "Slovak Republic": "421",
        "Slovenia": "386",
        "Commonwealth of the Northern M": "1-670",
        "Solomon Islands": "677",
        "Somalia": "252",
        "Sudan": "249",
        "Suriname": "597",
        "USА": "1",
        "Sierra Leone": "232",
        "Tajikistan": "992",
        "Taiwan": "886",
        "Thailand": "66",
        "Tanzania": "255",
        "Turks & Caicos Islands": "1-649",
        "Togolese Republic": "228",
        "Tokelau": "690",
        "Tonga": "676",
        "Trinidad and Tobago": "1-868",
        "Tuvalu": "688",
        "Tunisia": "21",
        "Turkmenistan": "993",
        "Turkey": "90",
        "Uganda": "256",
        "Uzbekistan": "998",
        "Ukraine": "380",
        "Uruguay": "598",
        "Faeroe Islands": "298",
        "Fiji": "679",
        "Philippines": "63",
        "Finland": "358",
        "Falkland Islands": "500",
        "France": "33",
        "French Guiana": "594",
        "French Polynesia": "689",
        "French Antilles": "590",
        "Croatia": "385",
        "Central African Republic": "236",
        "Chad": "235",
        "Czech Republic": "420",
        "Chile": "56",
        "Switzerland": "41",
        "Sweden": "46",
        "Sri Lanka": "94",
        "Ecuador": "593",
        "Equatorial Guinea": "240",
        "Wallis and Futuna": "681",
        "Eritrea": "291",
        "Estonia": "372",
        "Ethiopia": "251",
        "South Africa": "27",
        "Yugoslavia": "381",
        "Republic of Korea": "82",
        "Yemen, South": "969",
        "Jamaica": "1-876",
        "Japan": "81"
    ]
    
    private init() {}
    
}
